# Generated by Django 3.0.5 on 2020-04-08 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodData',
        ),
    ]
